import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "@/styles/global.scss";
import Header from "@/comnponents/header/header.component";

const ubuntu = Space_Grotesk({ subsets: ["latin"] });
interface RootLayoutProps {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={ubuntu.className}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}

export default RootLayout;